# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0002_entry_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='expiration',
            new_name='month',
        ),
    ]
