# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0003_auto_20170623_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
        migrations.AddField(
            model_name='product',
            name='active_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='front_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_gap',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='activated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
