# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0004_auto_20170623_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active_code',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='front_code',
            new_name='front',
        ),
    ]
